import { defineProducts } from './define';

export const apparel = defineProducts('Apparel', { gallery: ['hoodie'], sizes: ['S', 'M', 'L', 'XL', 'XXL'], condition: 'New with Tags' }, [
  {
    slug: 'supreme-box-logo-hooded-sweatshirt',
    brand: 'Supreme',
    name: 'Supreme Box Logo Hooded Sweatshirt',
    subcategory: 'Supreme',
    description: 'The Box Logo hoodie — the single most recognised piece in streetwear.',
    badge: 'GRAIL',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['supreme', 'box logo', 'bogo', 'hoodie', 'hooded sweatshirt'],
  },
  {
    slug: 'supreme-box-logo-tee',
    brand: 'Supreme',
    name: 'Supreme Box Logo Tee',
    subcategory: 'Supreme',
    description: 'The classic Box Logo tee in heavyweight cotton.',
    badge: 'CULT FAVORITE',
    tags: ['supreme', 'box logo', 'bogo', 'tee', 't-shirt'],
  },
  {
    slug: 'supreme-mm6-maison-margiela-box-logo-tee',
    brand: 'Supreme x MM6 Maison Margiela',
    name: 'Supreme x MM6 Maison Margiela Box Logo Tee',
    subcategory: 'Supreme',
    description: 'Margiela\u2019s deconstructed approach applied to the Supreme Box Logo.',
    badge: 'COLLECTOR PICK',
    highScarcity: true,
    tags: ['supreme', 'mm6', 'maison margiela', 'box logo', 'collab', 'tee'],
  },
  {
    slug: 'denim-tears-cotton-wreath-hoodie',
    brand: 'Denim Tears',
    name: 'Denim Tears Cotton Wreath Hoodie',
    subcategory: 'Denim Tears',
    description: 'Tremaine Emory\u2019s cotton wreath print — a symbol of the African diaspora — on a heavyweight hoodie.',
    badge: 'HIGH DEMAND',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['denim tears', 'cotton wreath', 'tremaine emory', 'hoodie'],
  },
  {
    slug: 'denim-tears-cotton-wreath-sweatpants',
    brand: 'Denim Tears',
    name: 'Denim Tears Cotton Wreath Sweatpants',
    subcategory: 'Denim Tears',
    description: 'All-over cotton wreath print sweatpants to match the hoodie.',
    badge: 'TRENDING',
    tags: ['denim tears', 'cotton wreath', 'sweatpants'],
  },
  {
    slug: 'corteiz-alcatraz-hoodie',
    brand: 'Corteiz',
    name: 'Corteiz Alcatraz Hoodie',
    subcategory: 'Corteiz',
    description: 'London\u2019s most talked-about label. The Alcatraz logo hoodie, drop-only.',
    badge: 'HIGH DEMAND',
    trending: true,
    highScarcity: true,
    tags: ['corteiz', 'crtz', 'alcatraz', 'hoodie', 'london'],
  },
  {
    slug: 'corteiz-alcatraz-tracksuit',
    brand: 'Corteiz',
    name: 'Corteiz Alcatraz Tracksuit',
    subcategory: 'Corteiz',
    description: 'Full Alcatraz tracksuit — jacket and pants.',
    badge: 'LIMITED RELEASE',
    tags: ['corteiz', 'crtz', 'alcatraz', 'tracksuit'],
  },
  {
    slug: 'stussy-8-ball-sherpa-fleece-jacket',
    brand: 'Stüssy',
    name: 'Stüssy 8 Ball Sherpa Fleece Jacket',
    subcategory: 'Stüssy',
    description: 'Reversible-feel sherpa fleece with the all-over 8 Ball motif.',
    badge: 'CULT FAVORITE',
    tags: ['stussy', 'stüssy', '8 ball', 'fleece', 'sherpa', 'jacket'],
  },
  {
    slug: 'jordan-nigel-sylvester-bike-air-jersey-sail',
    brand: 'Jordan x Nigel Sylvester',
    name: 'Jordan x Nigel Sylvester Jersey',
    subcategory: 'Jordan',
    description: 'Apparel from the Nigel Sylvester x Jordan collaboration, designed to pair with the AJ4.',
    badge: 'JUST DROPPED',
    newArrival: true,
    tags: ['jordan', 'nigel sylvester', 'jersey', 'bmx', 'collab'],
  },
  {
    slug: 'palace-tri-ferg-hood',
    brand: 'Palace',
    name: 'Palace Tri-Ferg Hood',
    subcategory: 'Palace',
    description: 'The Tri-Ferg logo hoodie from London skate brand Palace.',
    badge: 'TRENDING',
    tags: ['palace', 'tri-ferg', 'hoodie', 'skate'],
  },
  {
    slug: 'kith-williams-iii-hoodie',
    brand: 'Kith',
    name: 'Kith Williams III Hoodie',
    subcategory: 'Kith',
    description: 'Kith\u2019s signature heavyweight hoodie with the embroidered logo.',
    badge: 'COLLECTOR PICK',
    tags: ['kith', 'williams', 'hoodie', 'ronnie fieg'],
  },
]);
