import { defineProducts } from './define';

export const collectibles = defineProducts('Collectibles', { gallery: ['blind-box-case'], condition: 'New / Sealed' }, [
  {
    slug: 'popmart-the-monsters-big-into-energy-blind-box',
    brand: 'Pop Mart',
    name: 'LABUBU The Monsters Big Into Energy Vinyl Plush Blind Box',
    subcategory: 'LABUBU',
    collection: 'The Monsters — Big Into Energy',
    productType: 'Blind Box',
    gallery: ['plush'],
    description: 'LABUBU vinyl plush pendants from the Big Into Energy series. Sealed blind box.',
    badge: 'HIGH DEMAND',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['labubu', 'pop mart', 'popmart', 'the monsters', 'big into energy', 'blind box', 'kasing lung'],
  },
  {
    slug: 'popmart-the-monsters-exciting-macaron-blind-box',
    brand: 'Pop Mart',
    name: 'LABUBU The Monsters Exciting Macaron Vinyl Face Blind Box',
    subcategory: 'LABUBU',
    collection: 'The Monsters — Exciting Macaron',
    productType: 'Blind Box',
    gallery: ['plush'],
    description: 'The pastel macaron series that put LABUBU on every bag. Sealed blind box.',
    badge: 'CULT FAVORITE',
    highScarcity: true,
    tags: ['labubu', 'pop mart', 'popmart', 'the monsters', 'macaron', 'blind box'],
  },
  {
    slug: 'popmart-skullpanda-special-edition-sealed-case',
    brand: 'Pop Mart',
    name: 'SKULLPANDA Blind Box Sealed Case',
    subcategory: 'SKULLPANDA',
    collection: 'SKULLPANDA',
    productType: 'Sealed Case',
    description: 'A full sealed case of SKULLPANDA figures — chase odds intact.',
    badge: 'COLLECTOR PICK',
    trending: true,
    tags: ['skullpanda', 'pop mart', 'popmart', 'blind box', 'sealed case'],
  },
  {
    slug: 'popmart-crybaby-limited-sealed-case',
    brand: 'Pop Mart',
    name: 'CRYBABY Blind Box Sealed Case',
    subcategory: 'CRYBABY',
    collection: 'CRYBABY',
    productType: 'Sealed Case',
    description: 'Molly Lin\u2019s CRYBABY figures in a full sealed case.',
    badge: 'TRENDING',
    tags: ['crybaby', 'pop mart', 'popmart', 'blind box', 'sealed case'],
  },
  {
    slug: 'popmart-hacipupu-gummy-bear-sealed-case',
    brand: 'Pop Mart',
    name: 'HACIPUPU Blind Box Sealed Case',
    subcategory: 'HACIPUPU',
    collection: 'HACIPUPU',
    productType: 'Sealed Case',
    description: 'A full sealed case of HACIPUPU figures.',
    badge: 'JUST DROPPED',
    newArrival: true,
    tags: ['hacipupu', 'pop mart', 'popmart', 'blind box', 'sealed case'],
  },
  {
    slug: 'medicom-bearbrick-400-100-set',
    brand: 'Medicom Toy',
    name: 'BE@RBRICK 400% + 100% Set',
    subcategory: 'BE@RBRICK',
    collection: 'BE@RBRICK',
    productType: 'Designer Figure',
    description: 'The 400% and 100% BE@RBRICK pairing — the standard format for collab releases.',
    badge: 'COLLECTOR PICK',
    highScarcity: true,
    tags: ['bearbrick', 'be@rbrick', 'medicom', 'designer toy', 'vinyl'],
  },
  {
    slug: 'kaws-companion-open-edition-vinyl-figure',
    brand: 'KAWS',
    name: 'KAWS Companion Open Edition Vinyl Figure',
    subcategory: 'Designer Vinyl',
    collection: 'KAWS',
    productType: 'Designer Figure',
    description: 'The Companion — KAWS\u2019 signature character — as a boxed vinyl figure.',
    badge: 'GRAIL',
    highScarcity: true,
    tags: ['kaws', 'companion', 'designer vinyl', 'art toy'],
  },
  {
    slug: 'jellycat-bartholomew-bear',
    brand: 'Jellycat',
    name: 'Jellycat Bartholomew Bear',
    subcategory: 'Jellycat',
    collection: 'Jellycat',
    productType: 'Plush',
    gallery: ['plush'],
    description: 'The soft, round-bellied bear that became Jellycat\u2019s best-known character.',
    badge: 'TRENDING',
    tags: ['jellycat', 'bartholomew', 'bear', 'plush'],
  },
]);
