import { defineProducts } from './define';

const sizes = ['7', '8', '8.5', '9', '9.5', '10', '10.5', '11', '12', '13'];

export const sneakers = defineProducts('Sneakers', { gallery: ['sneaker'], sizes, condition: 'New / Deadstock' }, [
  // Travis Scott
  {
    slug: 'travis-scott-air-jordan-1-low-og-shy-pink',
    brand: 'Jordan x Travis Scott',
    name: 'Travis Scott x Air Jordan 1 Low OG "Shy Pink"',
    subcategory: 'Travis Scott',
    colourway: 'Sail / Shy Pink / Dark Mocha',
    description: 'The reverse-Swoosh Cactus Jack low in a soft pink and mocha colourway. One of the most requested Travis Scott pairs.',
    badge: 'HIGH DEMAND',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['travis scott', 'cactus jack', 'jordan 1', 'aj1 low', 'shy pink', 'reverse swoosh'],
  },
  {
    slug: 'travis-scott-air-jordan-1-low-og-tropical-pink',
    brand: 'Jordan x Travis Scott',
    name: 'Travis Scott x Air Jordan 1 Low OG "Tropical Pink"',
    subcategory: 'Travis Scott',
    colourway: 'Sail / Tropical Pink',
    description: 'A brighter take on the Cactus Jack low with tropical pink overlays and the signature backward Swoosh.',
    badge: 'TRENDING',
    trending: true,
    highScarcity: true,
    tags: ['travis scott', 'cactus jack', 'jordan 1', 'aj1 low', 'tropical pink', 'reverse swoosh'],
  },
  {
    slug: 'travis-scott-air-jordan-1-low-og-reverse-mocha',
    brand: 'Jordan x Travis Scott',
    name: 'Travis Scott x Air Jordan 1 Low OG "Reverse Mocha"',
    subcategory: 'Travis Scott',
    colourway: 'Sail / University Red / Ridgerock',
    description: 'Sail leather with mocha suede overlays — the Cactus Jack low that set the standard for the series.',
    badge: 'GRAIL',
    highScarcity: true,
    tags: ['travis scott', 'cactus jack', 'jordan 1', 'aj1 low', 'reverse mocha'],
  },
  // Jordan
  {
    slug: 'jordan-4-nigel-sylvester-brick-after-brick',
    brand: 'Jordan x Nigel Sylvester',
    name: 'Nigel Sylvester x Air Jordan 4 "Brick By Brick"',
    subcategory: 'Jordan',
    colourway: 'Sail / Brick Red',
    description: 'BMX icon Nigel Sylvester reworks the Air Jordan 4 with brick-toned suede and a deliberately worn-in finish.',
    badge: 'JUST DROPPED',
    featured: true,
    trending: true,
    newArrival: true,
    highScarcity: true,
    tags: ['nigel sylvester', 'jordan 4', 'aj4', 'brick by brick', 'bmx'],
  },
  {
    slug: 'nike-sb-air-jordan-4-pine-green',
    brand: 'Jordan x Nike SB',
    name: 'Nike SB x Air Jordan 4 "Pine Green"',
    subcategory: 'Jordan',
    colourway: 'White / Pine Green / Neutral Grey',
    description: 'The skate-ready AJ4 with a flexible build, white leather and pine green accents.',
    badge: 'COLLECTOR PICK',
    highScarcity: true,
    tags: ['nike sb', 'jordan 4', 'aj4', 'pine green', 'skate'],
  },
  {
    slug: 'jordan-4-retro-black-cat',
    brand: 'Jordan',
    name: 'Air Jordan 4 Retro "Black Cat"',
    subcategory: 'Jordan',
    colourway: 'Black / Black / Light Graphite',
    description: 'Tonal black nubuck from toe to heel. A modern classic and one of the most-searched AJ4s.',
    badge: 'CULT FAVORITE',
    trending: true,
    tags: ['jordan 4', 'aj4', 'black cat', 'retro'],
  },
  {
    slug: 'jordan-4-retro-white-cement',
    brand: 'Jordan',
    name: 'Air Jordan 4 Retro "White Cement"',
    subcategory: 'Jordan',
    colourway: 'White / Fire Red / Black / Tech Grey',
    description: 'The 1989 original colourway with speckled cement detailing and Nike Air on the heel.',
    badge: 'CULT FAVORITE',
    tags: ['jordan 4', 'aj4', 'white cement', 'og', 'retro'],
  },
  {
    slug: 'jordan-4-retro-toro-bravo',
    brand: 'Jordan',
    name: 'Air Jordan 4 Retro "Toro Bravo"',
    subcategory: 'Jordan',
    colourway: 'Fire Red / Black / Cement Grey',
    description: 'Bold fire red suede with black and cement accents — the AJ4 colourway collectors have waited years for.',
    badge: 'COMING SOON',
    status: 'Coming Soon',
    newArrival: true,
    tags: ['jordan 4', 'aj4', 'toro bravo', 'red', 'retro'],
  },
  {
    slug: 'jordan-3-retro-true-blue',
    brand: 'Jordan',
    name: 'Air Jordan 3 Retro "True Blue"',
    subcategory: 'Jordan',
    colourway: 'White / True Blue / Cement Grey',
    description: 'White leather, elephant print and true blue accents on the Tinker Hatfield classic.',
    badge: 'TRENDING',
    tags: ['jordan 3', 'aj3', 'true blue', 'elephant print', 'retro'],
  },
  {
    slug: 'jordan-11-retro-gamma-blue',
    brand: 'Jordan',
    name: 'Air Jordan 11 Retro "Gamma Blue"',
    subcategory: 'Jordan',
    colourway: 'Black / Gamma Blue / Varsity Maize',
    description: 'Black patent leather with gamma blue highlights — a holiday-season favourite.',
    badge: 'COMING SOON',
    status: 'Coming Soon',
    newArrival: true,
    tags: ['jordan 11', 'aj11', 'gamma blue', 'patent leather', 'retro'],
  },
  {
    slug: 'jordan-1-retro-high-og-chicago-lost-and-found',
    brand: 'Jordan',
    name: 'Air Jordan 1 Retro High OG "Lost & Found"',
    subcategory: 'Jordan',
    colourway: 'Varsity Red / Black / Sail / Muslin',
    description: 'The Chicago colourway with a vintage-inspired finish, cracked leather and aged midsole.',
    badge: 'COLLECTOR PICK',
    highScarcity: true,
    tags: ['jordan 1', 'aj1', 'chicago', 'lost and found', 'high og'],
  },
  // Nike / Kobe
  {
    slug: 'nike-kobe-8-protro-mambacurial',
    brand: 'Nike',
    name: 'Nike Kobe 8 Protro "Mambacurial"',
    subcategory: 'Kobe',
    colourway: 'Volt / Hyper Pink / Total Orange',
    description: 'A nod to Mercurial football boots, built on the lightweight Kobe 8 Protro.',
    badge: 'HIGH DEMAND',
    trending: true,
    highScarcity: true,
    tags: ['kobe', 'kobe 8', 'protro', 'mambacurial', 'mamba'],
  },
  {
    slug: 'nike-kobe-3-low-protro-fc-barcelona',
    brand: 'Nike x FC Barcelona',
    name: 'Nike Kobe 3 Low Protro x FC Barcelona',
    subcategory: 'Kobe',
    colourway: 'Blaugrana',
    description: 'Kobe meets Barça. The Kobe 3 Low Protro dressed in the club\u2019s blue and garnet.',
    badge: 'COMING SOON',
    status: 'Coming Soon',
    newArrival: true,
    tags: ['kobe', 'kobe 3', 'protro', 'barcelona', 'barca', 'football'],
  },
  {
    slug: 'nike-kobe-6-protro-grinch',
    brand: 'Nike',
    name: 'Nike Kobe 6 Protro "Grinch"',
    subcategory: 'Kobe',
    colourway: 'Green Apple / Volt / Crimson',
    description: 'The scaled green upper that became one of the most recognisable basketball shoes ever made.',
    badge: 'GRAIL',
    highScarcity: true,
    tags: ['kobe', 'kobe 6', 'protro', 'grinch', 'christmas'],
  },
  {
    slug: 'nike-kobe-5-protro-chaos',
    brand: 'Nike',
    name: 'Nike Kobe 5 Protro "Chaos"',
    subcategory: 'Kobe',
    colourway: 'Black / Varsity Red / White',
    description: 'Joker-inspired graphics on the low-cut Kobe 5 Protro.',
    badge: 'CULT FAVORITE',
    tags: ['kobe', 'kobe 5', 'protro', 'chaos', 'joker'],
  },
  // adidas
  {
    slug: 'adidas-forum-low-bad-bunny-blue-tint',
    brand: 'adidas x Bad Bunny',
    name: 'adidas Forum Low x Bad Bunny "Blue Tint"',
    subcategory: 'adidas',
    colourway: 'Blue Tint / Cream',
    description: 'Bad Bunny\u2019s Forum Low with the double-tongue design and ankle strap in a soft blue tint.',
    badge: 'TRENDING',
    trending: true,
    tags: ['adidas', 'bad bunny', 'forum', 'forum low', 'collab'],
  },
  {
    slug: 'adidas-samba-wales-bonner',
    brand: 'adidas x Wales Bonner',
    name: 'adidas Samba x Wales Bonner',
    subcategory: 'adidas',
    colourway: 'Cream / Green',
    description: 'Wales Bonner\u2019s crochet-detailed take on the Samba that sparked the terrace-shoe revival.',
    badge: 'LIMITED RELEASE',
    tags: ['adidas', 'samba', 'wales bonner', 'collab'],
  },
  // Other
  {
    slug: 'new-balance-990v4-jjjjound',
    brand: 'New Balance x JJJJound',
    name: 'New Balance 990v4 x JJJJound',
    subcategory: 'New Balance',
    colourway: 'Navy',
    description: 'Understated, made-in-USA 990v4 from Montreal studio JJJJound.',
    badge: 'COLLECTOR PICK',
    tags: ['new balance', '990', 'jjjjound', 'made in usa'],
  },
  {
    slug: 'salomon-xt-6',
    brand: 'Salomon',
    name: 'Salomon XT-6',
    subcategory: 'Salomon',
    colourway: 'Black / Phantom',
    description: 'The trail runner that crossed over into fashion. Quicklace, tough mesh and an aggressive outsole.',
    badge: 'CULT FAVORITE',
    tags: ['salomon', 'xt-6', 'gorpcore', 'trail'],
  },
  {
    slug: 'asics-gel-kayano-14',
    brand: 'ASICS',
    name: 'ASICS GEL-Kayano 14',
    subcategory: 'ASICS',
    colourway: 'White / Pure Silver',
    description: 'Late-2000s runner styling with metallic overlays — a cornerstone of the retro-running wave.',
    badge: 'TRENDING',
    tags: ['asics', 'kayano', 'gel-kayano 14', 'runner'],
  },
]);
