import { defineProducts } from './define';

export const soccer = defineProducts('Soccer', { gallery: ['jersey'], sizes: ['S', 'M', 'L', 'XL', 'XXL'], condition: 'New with Tags' }, [
  {
    slug: 'cactus-jack-fc-barcelona-limited-edition-jersey',
    brand: 'Cactus Jack x FC Barcelona',
    name: 'FC Barcelona x Cactus Jack Limited Edition Jersey',
    subcategory: 'FC Barcelona',
    description: 'Travis Scott\u2019s Cactus Jack logo across the Blaugrana — the El Clásico special edition.',
    badge: 'GRAIL',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['barcelona', 'barca', 'cactus jack', 'travis scott', 'el clasico', 'jersey'],
  },
  {
    slug: 'nike-fc-barcelona-re-issue-2005-06-ronaldinho-10-home-jersey',
    brand: 'Nike x FC Barcelona',
    name: 'FC Barcelona 2005-06 Ronaldinho #10 Home Reissue',
    subcategory: 'FC Barcelona',
    description: 'The reissued 2005-06 home shirt with Ronaldinho\u2019s #10 — the Ballon d\u2019Or season.',
    badge: 'CULT FAVORITE',
    trending: true,
    highScarcity: true,
    tags: ['barcelona', 'barca', 'ronaldinho', 'reissue', 'retro', 'jersey'],
  },
  {
    slug: 'argentina-messi-10-home-jersey',
    brand: 'adidas',
    name: 'Argentina Messi #10 Home Jersey',
    subcategory: 'Argentina',
    description: 'The three-star Argentina home shirt with Messi #10.',
    badge: 'HIGH DEMAND',
    tags: ['argentina', 'messi', 'world cup', 'jersey', 'adidas'],
  },
  {
    slug: 'psg-jordan-fourth-jersey',
    brand: 'Jordan x Paris Saint-Germain',
    name: 'Paris Saint-Germain x Jordan Fourth Jersey',
    subcategory: 'PSG',
    description: 'The Jumpman on the Parisian kit — the crossover that redefined football as streetwear.',
    badge: 'TRENDING',
    tags: ['psg', 'paris saint-germain', 'jordan', 'jumpman', 'fourth kit', 'jersey'],
  },
  {
    slug: 'real-madrid-y-3-fourth-jersey',
    brand: 'Y-3 x Real Madrid',
    name: 'Real Madrid x Y-3 Fourth Jersey',
    subcategory: 'Real Madrid',
    description: 'Yohji Yamamoto\u2019s Y-3 design language on a special-edition Real Madrid kit.',
    badge: 'LIMITED RELEASE',
    highScarcity: true,
    tags: ['real madrid', 'y-3', 'yohji yamamoto', 'fourth kit', 'jersey'],
  },
  {
    slug: 'brazil-2002-ronaldo-9-retro-jersey',
    brand: 'Nike',
    name: 'Brazil 2002 Ronaldo #9 Retro Jersey',
    subcategory: 'Brazil',
    description: 'The canary yellow of Brazil\u2019s 2002 World Cup win, with R9 on the back.',
    badge: 'CULT FAVORITE',
    tags: ['brazil', 'ronaldo', 'r9', '2002', 'world cup', 'retro', 'jersey'],
  },
  {
    slug: 'fc-barcelona-messi-10-retro-jersey',
    brand: 'Nike x FC Barcelona',
    name: 'FC Barcelona Messi #10 Retro Jersey',
    subcategory: 'FC Barcelona',
    description: 'A retro Barça home shirt with Messi #10 from his Camp Nou era.',
    badge: 'COLLECTOR PICK',
    tags: ['barcelona', 'barca', 'messi', 'retro', 'jersey'],
  },
  {
    slug: 'kith-adidas-messi-football-graphic-tee-black',
    brand: 'Kith x adidas',
    name: 'Kith x adidas Messi Football Graphic Tee',
    subcategory: 'Messi',
    description: 'Graphic tee from the Kith x adidas Messi collaboration.',
    badge: 'JUST DROPPED',
    newArrival: true,
    tags: ['kith', 'adidas', 'messi', 'tee', 'collab'],
  },
]);
