import { defineProducts } from './define';

export const tradingCards = defineProducts('Trading Cards', { gallery: ['trading-card-box'], condition: 'Factory Sealed' }, [
  {
    slug: 'pokemon-prismatic-evolutions-elite-trainer-box',
    brand: 'Pokémon',
    name: 'Prismatic Evolutions Elite Trainer Box',
    subcategory: 'Pokémon',
    productType: 'Elite Trainer Box',
    collection: 'Scarlet & Violet — Prismatic Evolutions',
    description: 'The Eeveelution-focused special set. Booster packs, sleeves, dice and accessories, factory sealed.',
    badge: 'HIGH DEMAND',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['pokemon', 'pokémon', 'prismatic evolutions', 'etb', 'elite trainer box', 'eevee', 'sealed'],
  },
  {
    slug: 'pokemon-prismatic-evolutions-pokemon-center-elite-trainer-box',
    brand: 'Pokémon',
    name: 'Prismatic Evolutions Pokémon Center Elite Trainer Box',
    subcategory: 'Pokémon',
    productType: 'Elite Trainer Box',
    collection: 'Scarlet & Violet — Prismatic Evolutions',
    description: 'The Pokémon Center edition of the Prismatic ETB, with additional booster packs and a promo card.',
    badge: 'GRAIL',
    highScarcity: true,
    tags: ['pokemon', 'pokémon', 'prismatic evolutions', 'pokemon center', 'etb', 'elite trainer box', 'sealed'],
  },
  {
    slug: 'pokemon-151-ultra-premium-collection',
    brand: 'Pokémon',
    name: 'Pokémon 151 Ultra-Premium Collection',
    subcategory: 'Pokémon',
    productType: 'Premium Collection',
    collection: 'Scarlet & Violet — 151',
    description: 'Metal Mew cards, a playmat and sixteen 151 booster packs in a collector presentation box.',
    badge: 'COLLECTOR PICK',
    trending: true,
    highScarcity: true,
    tags: ['pokemon', 'pokémon', '151', 'upc', 'ultra premium collection', 'mew', 'sealed'],
  },
  {
    slug: 'pokemon-151-booster-bundle',
    brand: 'Pokémon',
    name: 'Pokémon 151 Booster Bundle',
    subcategory: 'Pokémon',
    productType: 'Booster Bundle',
    collection: 'Scarlet & Violet — 151',
    gallery: ['trading-card-pack'],
    description: 'Six booster packs from the original-151 themed set, sealed.',
    badge: 'TRENDING',
    tags: ['pokemon', 'pokémon', '151', 'booster bundle', 'sealed'],
  },
  {
    slug: 'pokemon-celebrations-elite-trainer-box',
    brand: 'Pokémon',
    name: 'Celebrations Elite Trainer Box',
    subcategory: 'Pokémon',
    productType: 'Elite Trainer Box',
    collection: 'Sword & Shield — Celebrations',
    description: 'The 25th anniversary ETB, including Classic Collection reprints of iconic cards.',
    badge: 'CULT FAVORITE',
    highScarcity: true,
    tags: ['pokemon', 'pokémon', 'celebrations', '25th anniversary', 'etb', 'elite trainer box', 'sealed'],
  },
  {
    slug: 'one-piece-op05-awakening-of-the-new-era-booster-box',
    brand: 'One Piece Card Game',
    name: 'One Piece OP-05 Awakening of the New Era Booster Box',
    subcategory: 'One Piece',
    productType: 'Booster Box',
    collection: 'OP-05',
    gallery: ['booster-box'],
    description: 'Japanese-favourite set featuring Luffy Gear 5. 24 packs, factory sealed.',
    badge: 'GRAIL',
    trending: true,
    highScarcity: true,
    tags: ['one piece', 'op-05', 'op05', 'awakening of the new era', 'booster box', 'luffy', 'sealed'],
  },
  {
    slug: 'one-piece-op09-emperors-in-the-new-world-booster-box',
    brand: 'One Piece Card Game',
    name: 'One Piece OP-09 Emperors in the New World Booster Box',
    subcategory: 'One Piece',
    productType: 'Booster Box',
    collection: 'OP-09',
    gallery: ['booster-box'],
    description: 'The Four Emperors set. 24 packs, factory sealed.',
    badge: 'HIGH DEMAND',
    highScarcity: true,
    tags: ['one piece', 'op-09', 'op09', 'emperors in the new world', 'booster box', 'shanks', 'sealed'],
  },
  {
    slug: 'one-piece-op10-royal-blood-booster-box',
    brand: 'One Piece Card Game',
    name: 'One Piece OP-10 Royal Blood Booster Box',
    subcategory: 'One Piece',
    productType: 'Booster Box',
    collection: 'OP-10',
    gallery: ['booster-box'],
    description: 'A newer One Piece set. 24 packs, factory sealed.',
    badge: 'JUST DROPPED',
    newArrival: true,
    tags: ['one piece', 'op-10', 'op10', 'royal blood', 'booster box', 'sealed'],
  },
  {
    slug: 'panini-prizm-fifa-world-cup-qatar-2022-hobby-box',
    brand: 'Panini',
    name: 'Panini Prizm FIFA World Cup Qatar 2022 Hobby Box',
    subcategory: 'Panini',
    productType: 'Hobby Box',
    collection: 'Prizm World Cup',
    gallery: ['sports-card-box'],
    description: 'The Qatar World Cup Prizm release, home to Messi, Mbappé and a generation of rookie cards.',
    badge: 'COLLECTOR PICK',
    tags: ['panini', 'prizm', 'world cup', 'qatar 2022', 'hobby box', 'soccer cards', 'sealed'],
  },
  {
    slug: 'panini-2026-prizm-fifa-world-cup-hobby-preferred-box',
    brand: 'Panini',
    name: 'Panini Prizm FIFA World Cup 2026 Hobby Box',
    subcategory: 'Panini',
    productType: 'Hobby Box',
    collection: 'Prizm World Cup',
    gallery: ['sports-card-box'],
    description: 'Prizm for the 2026 World Cup. We\u2019ll list it here once details are confirmed.',
    badge: 'COMING SOON',
    status: 'Coming Soon',
    newArrival: true,
    tags: ['panini', 'prizm', 'world cup', '2026', 'hobby box', 'soccer cards'],
  },
  {
    slug: 'topps-chrome-uefa-club-competitions-hobby-box',
    brand: 'Topps',
    name: 'Topps Chrome UEFA Club Competitions Hobby Box',
    subcategory: 'Topps',
    productType: 'Hobby Box',
    collection: 'Topps Chrome UEFA',
    gallery: ['sports-card-box'],
    description: 'Champions League chrome with refractors, autographs and rookie cards of Europe\u2019s top talent.',
    badge: 'TRENDING',
    tags: ['topps', 'chrome', 'uefa', 'champions league', 'hobby box', 'soccer cards', 'sealed'],
  },
]);
