import { defineProducts } from './define';

export const watches = defineProducts('Watches', { gallery: ['watch'], condition: 'New / Unworn' }, [
  {
    slug: 'omega-swatch-moonswatch-mission-to-the-moon',
    brand: 'Omega x Swatch',
    name: 'MoonSwatch "Mission to the Moon"',
    subcategory: 'MoonSwatch',
    collection: 'Omega x Swatch',
    description: 'The Speedmaster-inspired bioceramic chronograph that started the MoonSwatch frenzy.',
    badge: 'HIGH DEMAND',
    featured: true,
    trending: true,
    highScarcity: true,
    tags: ['moonswatch', 'omega', 'swatch', 'speedmaster', 'mission to the moon', 'bioceramic'],
  },
  {
    slug: 'omega-swatch-moonswatch-mission-to-mercury',
    brand: 'Omega x Swatch',
    name: 'MoonSwatch "Mission to Mercury"',
    subcategory: 'MoonSwatch',
    collection: 'Omega x Swatch',
    description: 'Grey and silver tones inspired by the closest planet to the sun.',
    badge: 'COLLECTOR PICK',
    tags: ['moonswatch', 'omega', 'swatch', 'mission to mercury', 'bioceramic'],
  },
  {
    slug: 'omega-swatch-moonswatch-mission-to-mars',
    brand: 'Omega x Swatch',
    name: 'MoonSwatch "Mission to Mars"',
    subcategory: 'MoonSwatch',
    collection: 'Omega x Swatch',
    description: 'Red bioceramic case with grey sub-dials — the Red Planet edition.',
    badge: 'TRENDING',
    tags: ['moonswatch', 'omega', 'swatch', 'mission to mars', 'bioceramic'],
  },
  {
    slug: 'blancpain-swatch-scuba-fifty-fathoms',
    brand: 'Blancpain x Swatch',
    name: 'Blancpain x Swatch Scuba Fifty Fathoms',
    subcategory: 'Swatch Collab',
    collection: 'Blancpain x Swatch',
    description: 'The Fifty Fathoms dive watch reimagined in bioceramic, with an automatic movement.',
    badge: 'LIMITED RELEASE',
    trending: true,
    tags: ['blancpain', 'swatch', 'fifty fathoms', 'dive watch', 'bioceramic'],
  },
  {
    slug: 'timex-mm6-maison-margiela-limited-collaboration-watch',
    brand: 'Timex x MM6 Maison Margiela',
    name: 'Timex x MM6 Maison Margiela Watch',
    subcategory: 'Timex Collab',
    collection: 'Timex x MM6 Maison Margiela',
    description: 'Margiela\u2019s minimalist, reversed-out take on the classic Timex.',
    badge: 'COLLECTOR PICK',
    highScarcity: true,
    tags: ['timex', 'mm6', 'maison margiela', 'collab', 'watch'],
  },
  {
    slug: 'timex-noah-limited-collaboration-watch',
    brand: 'Timex x Noah',
    name: 'Timex x Noah Watch',
    subcategory: 'Timex Collab',
    collection: 'Timex x Noah',
    description: 'Noah\u2019s nautical-inspired details on a vintage-style Timex.',
    badge: 'CULT FAVORITE',
    tags: ['timex', 'noah', 'collab', 'watch'],
  },
  {
    slug: 'casio-limited-g-shock-collaboration',
    brand: 'G-SHOCK',
    name: 'G-SHOCK DW-5600 Collaboration Edition',
    subcategory: 'G-SHOCK',
    collection: 'G-SHOCK Collaborations',
    description: 'The square DW-5600 — the go-to canvas for G-SHOCK collaborations.',
    badge: 'JUST DROPPED',
    newArrival: true,
    tags: ['g-shock', 'casio', 'dw-5600', 'collab', 'watch'],
  },
]);
